Moved teardown() to own try/catch block. Refined failure type. Allowed test suite to continue on failed test case

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -1,6 +1,7 @@
 # Add more tests here
 TESTS=\
-	test_ExampleTest
+	test_ExampleTest \
+	test_ExampleTest2
 
 CXX ?= g++
 CXXFLAGS ?= -g -std=c++17 -I..
@@ -9,15 +10,25 @@ all: ${TESTS}
 
 check: all
 	@F="0"; \
-		for T in ${TESTS}; do echo -en "\n$$T: "; ./$$T 2> $$T.log; F=$$(($$F+$$?)); done; \
-		echo -e '\n-----'; echo "Failed tests: $$F"; echo '-----'; \
+		for T in ${TESTS}; do echo -n "\n$$T: "; ./$$T 2> $$T.log; F=$$(($$F+$$?)); done; \
+		echo '\n-----'; echo "Failed tests: $$F"; echo '-----'; \
 		[ $$F -eq 0 ]
 
 EXAMPLE_TEST_SRC = \
 	getbaud.cc \
 	ExampleTest.cc
+
+EXAMPLE_TEST_2_SRC = \
+	getbaud.cc \
+	ExampleTest2.cc
+
+
 test_ExampleTest: $(EXAMPLE_TEST_SRC)
 	$(CXX) $(CXXFLAGS) -DOUTPUT=\"$@\" -o $@ ../uunit.cc $(EXAMPLE_TEST_SRC)
+
+test_ExampleTest2: $(EXAMPLE_TEST_2_SRC)
+	$(CXX) $(CXXFLAGS) -DOUTPUT=\"$@\" -o $@ ../uunit.cc $(EXAMPLE_TEST_2_SRC)
+
 
 clean:
 	rm -f ${TESTS}
